github_username = "LaTartaRugaa"
github_repository = "Lastmanagement-System"
github_db_file_path = "db.json"
github_log_file_path = "data_log.json"
github_access_email = ""
github_token = ""
wattpilot_password = ""
wattpilot_ip = ""